### ISSUE TITLE
search query adds "x"

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-SearchSolr#10]
After a fresh install of this module on a new site, there is a "x' added to each search query with solr.

Searching "comple" seems to lauch a search for "complex" (but there is no result even if "complex" is present in the searchable items.

![image](https://user-images.githubusercontent.com/5262986/178468763-40bd7487-47b9-4713-ad9e-5251a5be14b6.png)

The same in the admin side but you can see a space is automatically added (maybe that why there is no result in the public side).

![image](https://user-images.githubusercontent.com/5262986/178468796-f0478f91-15ac-4531-aa7c-9ea7ab1874fa.png)

**Comment by pprw** [comment]
I am still affected by this.

I tried to create a new core, same result. I am using Omeka S 3.2.3, Advanced Search adapter for Solr 3.5.37.3, Advanced Search 3.3.6.18 (all up to the today date).

Any idea for me to try ?

**Comment by Daniel-KM** [comment]
This is not a x, this is a cross to remove the filter. Maybe the css can be improved.

**Comment by Daniel-KM** [comment]
This is fixed in last version of Advanced Search (3.4.6.19).
