### ISSUE TITLE
Solr HTTP error with localhost

### ISSUE THREAD

**Issue by mquantin** [Daniel-KM/Omeka-S-module-SearchSolr#11]
After configuring, I get an error 
`Solr HTTP error: Solr core is not available. Check config to get Solr core schema "http://omeka_admin:1".`

There are 2 differents base URL (see screenshot below).
![screenshot](https://user-images.githubusercontent.com/11961831/221892994-3322eb3b-71a5-4698-b5d4-3e4ea7f19484.png)

**-> What is this schema URL `http://omeka_admin:1` in my error?** 

When I request the schema through the terminal (with the right URL), it works:
```bash
curl --user 'omeka_admin:password' 'http://localhost:8983/solr/omeka/schema'
{
  "responseHeader":{
    "status":0,
    "QTime":20},
  "schema":{
    "name":"default-config",
etc.
```

Where is the schema URL rewritten to that wrong one? 

In the config page, the set URL is the right one `http://localhost:8983/solr/omeka`
The credentials are OK

When I try to create a new core, I get the same error, right after the first step (field "name").

**Comment by Daniel-KM** [comment]
In this case, you can try "127.0.0.1".
