### ISSUE TITLE
possibly false error message?

### ISSUE THREAD

**Issue by GarrettArm** [Daniel-KM/Omeka-S-module-SearchSolr#12]
SearchSolr module v3.5.40.4 running on Omeka 4.0.1 gives the following error message on the Modules page:

`A new version of this module is available. [Get the new version.](https://gitlab.com/Daniel-KM/Omeka-S-module-SearchSolr)`

However, the linked url points to SearchSolr v3.5.15.  Which is a prior release to v3.5.40.4

I am downloading the packages from this git repo instead of the gitlab repo, if that makes a difference.

**Comment by Daniel-KM** [comment]
This is an issue on module Generic. It doesn't occur anymore for this module, since it is numbered x.x.x.
