### ISSUE TITLE
external solr server. 

### ISSUE THREAD

**Issue by jamesbiasemory** [Daniel-KM/Omeka-S-module-SearchSolr#2]
Is there anything else I would need to change to make it use an external solr server?
Also would changing the scheme to https work?

Would it be possible at some point to add either a config file or an Omeka admin interface to configure this? 

    protected function getSolrCoreDefaultSettings()
    {
        return [
            'client' => [
                'scheme' => 'http',
                'host' => 'localhost',
                'port' => 8983,
                'path' => '/',
                // 'collection' => null,
                'core' => 'omeka',
                'username' => null,
                'password' => null,
            ],
            'is_public_field' => 'is_public_b',
            'resource_name_field' => 'resource_name_s',
            'sites_field' => 'site_id_is',
        ];
    }

**Comment by Daniel-KM** [comment]
You don't need anything specific to make it working, to fill the form should be enough, isn't it?
![image](https://user-images.githubusercontent.com/2138485/92759960-8b87e280-f390-11ea-8ac5-de250460a52c.png)

**Comment by jamesbiasemory** [comment]
thank you for getting back to me. I do not have a configure button on my installation in the modules menu. 
thats what was confusing me. 
I found it, thanks so much!
