### ISSUE TITLE
Item sets displayed on results page even though item sets were not set for indexing

### ISSUE THREAD

**Issue by mariusst** [Daniel-KM/Omeka-S-module-SearchSolr#4]
Item sets were not checked in the checkbox of the index settings from the Search module, but they are displayed first in the search results. To test this bug please make a search in our dev installation at this link https://dev.bibliotecaarad.ro/s/periodice/cautare

My setup:
- Ubuntu 18.04
- Apache 2.4.29
- Mysql 5.7.32
- Solr 8.7.0
- Omeka S 3.0.1
- Search 3.5.15.3.4
-  jQueryUI 1.12.1
- Reference 3.4.23.3.3
- Generic module 3.3.26
- SearchSolr 3.5.15.3.7

**Comment by Daniel-KM** [comment]
It's strange; if item sets are in the results, it means that they were indexed inside Solr. Did you reset the Solr index? Can you do a full reindexation (in Search > reindex all), without setting a number in the sidebar)?

**Comment by mariusst** [comment]
I did a re-index and have the same problem.

I also noticed that even if you navigate to the next page of the search results the item sets are displayed, as if they are not part of the results page but rather hard coded into the template page.

**Comment by Daniel-KM** [comment]
I find the issue, I'm fixing it.

**Comment by Daniel-KM** [comment]
The fix will be released Monday.

**Comment by Daniel-KM** [comment]
There is a fix for Search.
I'll release them as a new version once you indicate the issues are fixed.

**Comment by mariusst** [comment]
I reinstalled the module with the latest commit https://github.com/Daniel-KM/Omeka-S-module-SearchSolr/commit/6eca5611272c65e0c38c6b49ca1824679ad94cdb and I reindexed. The issue is still present

**Comment by Daniel-KM** [comment]
I find the issue, it's only a template one: when there is no results, it displays all resources... It's not related to this module, but to Search. See Daniel-KM/Omeka-S-module-Search@c66bdf5.
