### ISSUE TITLE
Item sets, resource class and resource template filter not working

### ISSUE THREAD

**Issue by mariusst** [Daniel-KM/Omeka-S-module-SearchSolr#5]
If i try to make a search for a keyword and filter the results using either item sets, resource class or resource template filter I get the following errors and no search results:

> Query error: Solr HTTP error: OK (400) { "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"undefined field item_set_id_field", "code":400}} Query:{ "query": "Aradul nou", "resources": [ "items" ], "is_public": false, "filters": { "item_set_id_field": [ [ "86977", "86995", "87001" ] ] }, "date_range_filters": [], "filter_queries": [], "sort": "dcterms_title_s asc", "offset": 0, "limit": 100, "facet_fields": [ "dcterms_title_s", "dcterms_creator_ss", "dcterms_date_s" ], "facet_limit": 10, "facet_languages": [], "excluded_fields": [], "site_id": 7 }

> Query error: Solr HTTP error: OK (400) { "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"undefined field resource_class_id_field", "code":400}} Query:{ "query": "Aradul nou", "resources": [ "items" ], "is_public": false, "filters": { "resource_class_id_field": [ [ "bibo:Periodical" ] ] }, "date_range_filters": [], "filter_queries": [], "sort": "dcterms_title_s asc", "offset": 0, "limit": 100, "facet_fields": [ "dcterms_title_s", "dcterms_creator_ss", "dcterms_date_s" ], "facet_limit": 10, "facet_languages": [], "excluded_fields": [], "site_id": 7 }

> Query error: Solr HTTP error: OK (400) { "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"undefined field resource_template_id_field", "code":400}} Query:{ "query": "Aradul nou", "resources": [ "items" ], "is_public": false, "filters": { "resource_template_id_field": [ [ "10" ] ] }, "date_range_filters": [], "filter_queries": [], "sort": "dcterms_title_s asc", "offset": 0, "limit": 100, "facet_fields": [ "dcterms_title_s", "dcterms_creator_ss", "dcterms_date_s" ], "facet_limit": 10, "facet_languages": [], "excluded_fields": [], "site_id": 7 }

My setup:
- Ubuntu 18.04
- Apache 2.4.29
- Mysql 5.7.32
- Solr 8.7.0
- Omeka S 3.0.1
- Search 3.5.15.3.4
-  jQueryUI 1.12.1
- Reference 3.4.23.3.3
- Generic module 3.3.26
- SearchSolr 3.5.15.3.7

**Comment by Daniel-KM** [comment]
Yes, here the fields are undefined. Can you show me the config of the search page ? Or try to resave it first.

**Comment by mariusst** [comment]
Here is a screenshot of the config search page
![Searchconfig](https://user-images.githubusercontent.com/414526/100059212-5d645b80-2e33-11eb-9c33-1e0e84871b94.jpg)

**Comment by Daniel-KM** [comment]
Indeed, the issues are indicated in the form : the item set id, the resource class id and the template id should be added in fields, so I had the same issue and I added this message in the form because it was simpler to fix in the config of the form than in the module. It will be a future improvement, but for now, it's only a message. So use a form that manages these three fields (even if they are not displayed). 

Note that it is better to use `_ss` for facets (`_s` means that only the first value can be a facet).

**Comment by Daniel-KM** [comment]
Indeed, the issues are indicated in the form : the item set id, the resource class id and the template id should be added in fields, so I had the same issue and I added this message in the form because it was simpler to fix in the config of the form than in the module. It will be a future improvement, but for now, it's only a message. So use a form that manages these three fields (even if they are not displayed).

**Comment by mariusst** [comment]
Daniel, thank you for you answer but I'm not sure if I understood. Are these filters fixable or yet to be implemented? If they are fixable, what do I have to do to add the ids in the fields and what form to use and where?

**Comment by Daniel-KM** [comment]
No, they are already implemented. In fact, the module Search doesn't know the config of Solr. So you have to include them in the config of Solr: 
![image](https://user-images.githubusercontent.com/2138485/100394460-848e7900-303d-11eb-8ca7-8455c82d515d.png)
then choose it in the search form. 

The option can be set automatically if you use special form, like the [PSL Search Form](https://github.com/Daniel-KM/omeka-s-module-PslSearchForm). In a next version, I'll include them directly in Search to simplify.

**Comment by mariusst** [comment]
I added the Item set field in Solr config. Then I did a reindex of solr, but still get the same error. If I check the schema in the admin interface of solr I don't see no Item Set field there. Please check the attached screenshots

I'm only interested in Item set filter, but I also set and tested the template and resource class filters and have the same problem

![Screenshot from 2020-11-30 11-59-16](https://user-images.githubusercontent.com/414526/100597462-29db7280-3306-11eb-9c8e-446baa46cc24.png)

![Screenshot from 2020-11-30 12-15-00](https://user-images.githubusercontent.com/414526/100597470-2cd66300-3306-11eb-9280-9b776b163883.png)

![Screenshot from 2020-11-30 12-23-36](https://user-images.githubusercontent.com/414526/100598090-efbea080-3306-11eb-9df6-8c41c67ba7fe.png)
