### ISSUE TITLE
cloudsearch

### ISSUE THREAD

**Issue by jamesbiasemory** [Daniel-KM/Omeka-S-module-SearchSolr#6]
AWS cloudsearch has full lucene compatible search but I can't get it to work with your plugin because it adds /solr to every path. 
When I changed the core name to be /2013-01-01/ which cloudsearch needs instead of /solr, it adds /solr/2013-01-01/ onto every path. 
I don't think anything about how it handles data would need to be changed just how it asks for it. 

Here is an example of a cloudsearch api call for lucene. 
https://s-omeka-safjskljsdfkjsdf.us-east-2.cloudsearch.amazonaws.com/2013-01-01/search?q.parser=lucene&q="SEARCHTERM"

So if you could allow the full path  after the domain name to be edited I think this will work with cloudsearch.
Although would each query need to be modified in the code to include ?q.parser=lucene& or could I add that to the "core name"?

**Comment by Daniel-KM** [comment]
I don't find the place where "/solr/" is added, except for the link in the [admin board](https://github.com/Daniel-KM/Omeka-S-module-SearchSolr/blob/master/src/Api/Representation/SolrCoreRepresentation.php#L176-L185), and to get the [client url](https://github.com/Daniel-KM/Omeka-S-module-SearchSolr/blob/master/src/Api/Representation/SolrCoreRepresentation.php#L165), that is used only to get the schema, not for queries. The queries uses the Solarium library to make the link between Omeka and Solr. 
So can you try to change [this line](https://github.com/Daniel-KM/Omeka-S-module-SearchSolr/blob/master/src/Api/Representation/SolrCoreRepresentation.php#L165) with 2013-01-01?

**Comment by jamesbiasemory** [comment]
thanks will try it when I get a chance.
