### ISSUE TITLE
simple query not working

### ISSUE THREAD

**Issue by JorisLambrechts** [Daniel-KM/Omeka-S-module-SearchSolr#7]
I've setup solr (8.6.3) and managed to index my data. So everything seems fine.

I can do filter searches correctly but when I try a simple search like ?q=test, I get no results. Leaving q empty returns all results.

All used fields are indexed, as text (_t), so there should be results in the index.

I'm thinking that my solrconfig.xml is not correct because I also get the following warning in the mapping form:
_This core seems to have no default field. If there are no results to a default query, add the copy field "_text_" with source "*"._

Is there an example of a working solrconfig.xml?

**Comment by Daniel-KM** [comment]
The default solrconfig.xml is working fine, but see this issue on the forum: https://forum.omeka.org/t/search-field-doesnt-return-results-with-solr/11650/12

**Comment by JorisLambrechts** [comment]
Thanks, that fixed it.
