### ISSUE TITLE
Edit Mapping Error

### ISSUE THREAD

**Issue by jbuwlaw** [Daniel-KM/Omeka-S-module-SearchSolr#9]
I believe this issue should be posted here and not in the search module, but if I am mistaken please let me know.
When I click to edit a mapping 
Solr cores -> resource list for core -> Maps for (items or item sets) -> edit any map
I receive the following error:
Fatal error: Declaration of DoctrineProxies\__CG__\SearchSolr\Entity\SolrCore::getId() must be compatible with SearchSolr\Entity\SolrCore::getId(): ?int in /opt/omeka-s/modules/SearchSolr/data/doctrine-proxies/__CG__SearchSolrEntitySolrCore.php on line 182

SearchSolr version: 3.5.20.3 
Search version:  3.5.18.3
Omeka S version: 3.0.1

Thanks for all your hard work!

**Comment by Daniel-KM** [comment]
Thanks this is fixed in 3.5.21.3.
